test:
  sessions:
    clients:
      database: cloud_model_test
      hosts:
        - localhost:27017
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
development:
  clients:
    default:
      database: cloud_model_development
      hosts:
        - localhost:27017